[supervisord]
nodaemon=true

[program:Xvfb]
command=bash -c 'Xvfb $DISPLAY -screen 0 ${VNC_WIDTH}x${VNC_HEIGHT}x24 -nolisten unix'
stderr_logfile=/var/log/Xvfb.stderr.log
priority=1
autorestart=true

[program:Openbox]
command=openbox
priority=2
stderr_logfile=/var/log/openbox.err.log
autorestart=true

[program:VNC]
command=/config/start_vnc.sh
startsecs=5
autorestart=true
stderr_logfile=/var/log/x11vnc.stderr.log
priority=3

[program:Websockify]
command=/config/start_websockify.sh
startsecs=5
autorestart=true
stderr_logfile=/var/log/websockify.stderr.log
priority=4

[program:Singbox]
command=/config/start_singbox.sh
startsecs=3
autorestart=true
stderr_logfile=/var/log/singbox.err.log
priority=4

[program:Chrome]
command=sh -c "sleep 2 && /config/start_chrome.sh"
priority=5
autorestart=true
stderr_logfile=/var/log/chrome.err.log
